import { Inter } from "next/font/google";
import "./globals.css";
import Chatbot from "@/components/chatbot";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Brain Tumor detection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className='flex justify-end items-center'>
          <Chatbot />
        </div>
      </body>
    </html>
  );
}
